import Header from '@/src/components/header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/src/lib/utils';
import Footer from '@/src/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth selection:bg-primary selection:text-white">
      <body className={cn("relative ",inter.className)}>
        <Header />

        {/* <main className='min-h-screen '>{children}</main> */}
        <main className=''>{children}</main>

        <Footer/>
      </body>
    </html>
  );
}
