import Header from '@/components/header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import Footer from '@/components/footer';
import { ThemeProvider } from '../components/globals/dark-mode';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth selection:bg-primary selection:text-white">
      <body className={cn("relative text-muted-foreground overflow-x-hidden", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          {/* <main className='min-h-screen '>{children}</main> */}
          <main className=''>{children}</main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
